/** @type {import('next').NextConfig} */

const paths = [
  { path: "types-of-space-maintainers-for-kids", des: "blog" },
  { path: "root-canal-therapy-for-children", des: "blog" },
  { path: "will-fluoride-treatments-benefit-my-child", des: "blog" },
  { path:  "best-ways-to-keep-kids-teeth-aligned", des: "blog" },
  { path:  "the-prevention-of-tooth-decay", des: "blog" },
  { path:  "teeth-cleaning-vs-deep-cleaning", des: "blog" },
  { path:   "how-to-prevent-tooth-decay-in-kids", des: "blog" },
  { path:  "mouth-guards-and-protecting-childrens-teeth", des: "blog" },
  { path: "how-do-fluoride-treatments-benefit-my-child", des: "blog" },
  { path: "composite-fillings-vs-amalgams", des: "blog" },
  { path: "making-a-dental-appointment-during-covid-19", des: "blog" },
  { path:"teeth-grinding", des: "blog" },
  { path: "everything-that-you-need-to-know-about-pediatric-crowns", des: "blog" },
  { path: "benefits-of-dental-sealants-that-you-must-know", des: "blog" },
  { path: "effects-of-fluoride", des: "blog" },
  { path: "oral-care-in-infants", des: "blog" },
  { path: "orthodontics-for-kids", des: "blog" },
  { path: "pediatric-dentistry-for-kids", des: "blog" },
  { path: "womens-oral-health-during-pregnancy", des: "blog" },
  { path:  "what-happens-to-your-teeth-while-you-sleep", des: "blog" },
  { path: "dental-tips-before-and-during-vacation", des: "blog" },
  { path: "tooth-extraction-is-it-preventable", des: "blog" },
  { path: "how-to-help-a-teething-baby", des: "blog" },
  { path:  "healthy-oral-habits-for-school-kids", des: "blog" },
  { path: "do-i-need-dental-implants", des: "blog" },
  { path:  "different-types-of-anesthesia-used-in-dentistry", des: "blog" },
  { path:  "importance-of-pediatric-dentistry-for-kids", des: "blog" },
  { path: "pediatric-dentistry", des: "blog" },
  { path: "what-are-the-do-and-donts-of-infant-oral-health-care", des: "blog" },
  { path:  "building-good-oral-habits-in-children", des: "blog" },
  { path: "oral-sedation-for-kids-who-afraid-of-having-dental-work", des: "blog" },
  { path: "a-dentist-for-kids-pediatric-dentist-vs-general-dentist", des: "blog" },
  { path:  "temporomandibular-joint-disorder", des: "blog" },
  { path:  "what-is-surgical-dentistry", des: "blog" },
  { path: "importance-of-space-maintainers", des: "blog" },
  { path:"teaching-your-child-good-oral-habits-2", des: "blog" },
  { path: "is-your-child-anxious-to-see-the-dentist", des: "blog" },
  { path: "the-impact-of-sugar-on-childrens-teeth", des: "blog" },
  { path: "pacifier-usage-in-kids", des: "blog" },
  { path: "dental-crowns-for-kids-2", des: "blog" },
  { path:"what-does-a-pediatric-dentist-do", des: "blog" },
  { path: "space-maintainers-for-your-kids", des: "blog" },
  { path: "cavities-in-kids", des: "blog" },
  { path: "deep-cleaning-what-is-it-and-how-it-is-used", des: "blog" },
  { path: "root-canal-treatment-for-children-and-younger-adults", des: "blog" },
  { path: "pediatric-dentistry-for-adolescents-2", des: "blog" },
  { path:   "pros-and-cons-of-dental-sealants-for-kids", des: "blog" },
  { path:   "dental-sealants-for-kids", des: "blog" },
  { path:  "the-painful-process-of-teething-and-how-can-parents-help", des: "blog" },
  { path:  "dental-health-care-and-coronavirus-considerations", des: "blog" },
  { path:  "whendoes-pediatric-tooth-extraction-become-necessary", des: "blog" },
  { path:  "what-to-do-about-a-persistent-toothache", des: "blog" },
  { path:  "consider-dental-sealants", des: "blog" },
  { path:  "dental-crowns-variations-worth-considering", des: "blog" },
  { path:    "what-is-pediatric-pulp-therapy", des: "blog" },
  { path:  "debunking-myths-and-facts-about-nitrous-oxide-laughing-gas", des: "blog" },
  { path:  "benefits-of-space-maintainers-for-kids", des: "blog" },
  { path: "dental-crowns-for-kids", des: "blog" },
  { path: "signs-and-symptoms-of-teeth-decay-in-kids", des: "blog" },
  { path:  "tooth-decay-prevention-in-kids",des: "blog" },
  { path:"child-athletes-and-dental-health",des: "blog" },
  { path:  "baby-bottle-tooth-decay", des: "blog" },
  { path:  "how-to-properly-brush-and-floss", des: "blog" },
  { path:  "caring-for-your-childs-oral-health", des: "blog" },
  { path:   "what-to-do-on-your-childs-first-dental-visit", des: "blog" },
  { path:  "food-and-drinks-to-avoid-for-children", des: "blog" },
  { path:  "top-4-benefits-of-space-maintainers-for-kids", des: "blog" },
  { path: "tips-to-soothe-teething-infants", des: "blog" },
  { path:  "how-are-pediatric-dentists-different-from-general-dentists", des: "blog" },
  { path: "is-mouthwash-safe-for-children", des: "blog" },
  { path:   "safety-and-benefits-of-nitrous-oxide-sedation-for-kids", des: "blog" },
  { path:   "all-about-dental-sealants-for-kids", des: "blog" },
  { path:  "dental-space-maintainers-for-children", des: "blog" },
  { path:  "teaching-your-child-good-oral-habits", des: "blog" },
  { path: "when-do-kids-need-space-maintainers", des: "blog" },
  { path: "is-fluoride-safe-for-kids", des: "blog" },
  { path:  "how-to-prepare-your-child-for-tooth-extraction", des: "blog" },
  { path:  "root-canal-therapy", des: "blog" },
  { path: "what-are-dental-implants", des: "blog" },
  { path:  "childrens-dental-crowns", des: "blog" },
  { path:  "how-do-we-detect-early-tooth-decay-in-children", des: "blog" },
  { path:  "what-are-the-options-for-kids-dental-crowns", des: "blog" },
  { path:  "importance-of-fluoride-treatment-for-kids", des: "blog" },
  { path:  "understanding-bruxism-in-children", des: "blog" },
  { path: "learn-more-about-endodontics", des: "blog" },
  { path: "effects-of-thumb-sucking-on-childrens-oral-health", des: "blog" },
  { path:  "wisdom-tooth-extractions", des: "blog" },
  { path: "sealants-prevent-tooth-decay", des: "blog" },
  { path: "dental-crowns-for-children", des: "blog" },
  { path:"healthy-snacks-for-children", des: "blog" },
  { path:"do-sealants-prevent-tooth-decay", des: "blog" },
  { path:"what-are-dental-exams-and-x-rays", des: "blog" },
  { path:"what-are-pediatric-dental-pulp-complications", des: "blog" },
  { path:  "what-should-parents-know-about-fluoride-varnish", des: "blog" },
  { path: "dental-anxiety-in-children", des: "blog" },
  { path: "5-warning-signs-of-dental-emergency-in-children", des: "blog" },
  { path:"athletic-mouth-guards-are-protecting-your-childs-teeth", des: "blog" },
  { path: "everythingthat-you-need-to-know-about-pediatric-dental-fillings", des: "blog" },
  { path: "dental-flossing-for-kids", des: "blog" },
  { path: "how-long-does-a-root-canal-procedure-take", des: "blog" },
  { path: "what-is-root-canal-therapy", des: "blog" },
  { path: "best-food-for-your-kids-from-oral-health", des: "blog" },
  { path: "what-to-expect-when-you-take-your-child-for-a-dental-filling-procedure", des: "blog" },
  { path: "dental-insurance-for-dental-emergencies", des: "blog" },
  { path: "cracked-or-chipped-tooth", des: "blog" },
  { path: "parental-guide-to-prevent-tooth-decay-in-kids", des: "blog" },
  { path: "about-the-pediatric-dentistry-for-adolescents", des: "blog" },
  { path:  "why-does-my-child-have-tooth-pain",des: "blog" },
  { path:  "tips-to-prevent-tooth-decay-in-kids", des: "blog" },
  { path: "nitrous-oxide-sedation-in-kids-dentistry", des: "blog" },
  { path: "oral-cavities-in-kids", des: "blog" },
  { path:  "pediatric-dentistry-for-adolescents", des: "blog" },
  { path: "common-dental-problems-that-children-face", des: "blog" },
  { path:  "understanding-wisdom-tooth-removal", des: "blog" },
  { path:  "the-differences-between-metal-crowns-and-porcelain-crowns", des: "blog" },
  { path: "how-to-handle-a-dental-emergency", des: "blog" },
  { path:  "learn-more-about-pediatric-dentistry", des: "blog" },
  { path:  "tooth-extraction-in-kids-cause-and-treatment", des: "blog" },
  { path:   "everything-that-you-need-to-know-about-pediatric-dental-fillings", des: "blog" },


  { path: "dental-crowns", des: "services" },
  { path: "dental-filling", des: "services" },
  { path: "decay-prevention", des: "services" },
  { path: "dental-pulp-treatment", des: "services" },
  { path: "dental-sealants", des: "services" },
  { path: "emergency-dental-care", des: "services" },
  { path: "fluoride-treatment", des: "services" },
  { path: "infant-oral-care", des: "services" },
  { path: "nitrous-oxide", des: "services" },
  { path: "space-maintainers", des: "services" },
  { path: "tooth-extraction", des: "services" },


];




const BlogsPath = [
  // "types-of-space-maintainers-for-kids",
  // "root-canal-therapy-for-children",
  // "will-fluoride-treatments-benefit-my-child",
  // "best-ways-to-keep-kids-teeth-aligned",
  // "the-prevention-of-tooth-decay",
  // "teeth-cleaning-vs-deep-cleaning",
  // "how-to-prevent-tooth-decay-in-kids",
  // "mouth-guards-and-protecting-childrens-teeth",
  // "how-do-fluoride-treatments-benefit-my-child",
  // "composite-fillings-vs-amalgams",
  // "making-a-dental-appointment-during-covid-19",
  // "teeth-grinding",
  // "everything-that-you-need-to-know-about-pediatric-crowns",
  // "benefits-of-dental-sealants-that-you-must-know",
  // "effects-of-fluoride",
  // "oral-care-in-infants",
  // "orthodontics-for-kids",
  // "pediatric-dentistry-for-kids",
  // "womens-oral-health-during-pregnancy",
  // "what-happens-to-your-teeth-while-you-sleep",
  // "dental-tips-before-and-during-vacation",
  // "tooth-extraction-is-it-preventable",
  // "how-to-help-a-teething-baby",
  // "healthy-oral-habits-for-school-kids",
  // "do-i-need-dental-implants",
  // "different-types-of-anesthesia-used-in-dentistry",
  // "importance-of-pediatric-dentistry-for-kids",
  // "pediatric-dentistry",
  // "what-are-the-do-and-donts-of-infant-oral-health-care",
  // "building-good-oral-habits-in-children",
  // "oral-sedation-for-kids-who-afraid-of-having-dental-work",
  // "a-dentist-for-kids-pediatric-dentist-vs-general-dentist",
  // "temporomandibular-joint-disorder",
  // "what-is-surgical-dentistry",
  // "importance-of-space-maintainers",
  // "teaching-your-child-good-oral-habits-2",
  // "is-your-child-anxious-to-see-the-dentist",
  // "the-impact-of-sugar-on-childrens-teeth",
  // "pacifier-usage-in-kids",
  // "dental-crowns-for-kids-2",
  // "what-does-a-pediatric-dentist-do",
  // "space-maintainers-for-your-kids",
  // "cavities-in-kids",
  // "deep-cleaning-what-is-it-and-how-it-is-used",
  // "root-canal-treatment-for-children-and-younger-adults",
  // "pediatric-dentistry-for-adolescents-2",
  // "pros-and-cons-of-dental-sealants-for-kids",
  // "dental-sealants-for-kids",
  // "the-painful-process-of-teething-and-how-can-parents-help",
  // "dental-health-care-and-coronavirus-considerations",
  // "whendoes-pediatric-tooth-extraction-become-necessary",
  // "what-to-do-about-a-persistent-toothache",
  // "consider-dental-sealants",
  // "dental-crowns-variations-worth-considering",
  // "what-is-pediatric-pulp-therapy",
  // "debunking-myths-and-facts-about-nitrous-oxide-laughing-gas",
  // "benefits-of-space-maintainers-for-kids",
  // "dental-crowns-for-kids",
  // "signs-and-symptoms-of-teeth-decay-in-kids",
  // "tooth-decay-prevention-in-kids",
  // "child-athletes-and-dental-health",
  // "baby-bottle-tooth-decay",
  // "how-to-properly-brush-and-floss",
  // "caring-for-your-childs-oral-health",
  // "what-to-do-on-your-childs-first-dental-visit",
  // "food-and-drinks-to-avoid-for-children",
  // "top-4-benefits-of-space-maintainers-for-kids",
  // "tips-to-soothe-teething-infants",
  // "how-are-pediatric-dentists-different-from-general-dentists",
  // "is-mouthwash-safe-for-children",
  // "safety-and-benefits-of-nitrous-oxide-sedation-for-kids",
  // "all-about-dental-sealants-for-kids",
  // "dental-space-maintainers-for-children",
  // "teaching-your-child-good-oral-habits",
  // "when-do-kids-need-space-maintainers",
  // "is-fluoride-safe-for-kids",
  // "how-to-prepare-your-child-for-tooth-extraction",
  // "how-to-prepare-your-child-for-tooth-extraction",
  // "how-to-prepare-your-child-for-tooth-extraction",
  // "root-canal-therapy",
  // "what-are-dental-implants",
  // "childrens-dental-crowns",
  // "how-do-we-detect-early-tooth-decay-in-children",
  // "what-are-the-options-for-kids-dental-crowns",
  // "importance-of-fluoride-treatment-for-kids",
  // "understanding-bruxism-in-children",
  // "learn-more-about-endodontics",
  // "effects-of-thumb-sucking-on-childrens-oral-health",
  // "wisdom-tooth-extractions",
  // "sealants-prevent-tooth-decay",
  // "dental-crowns-for-children",
  // "healthy-snacks-for-children",
  // "do-sealants-prevent-tooth-decay",
  // "what-are-dental-exams-and-x-rays",
  // "what-are-pediatric-dental-pulp-complications",
  // "what-should-parents-know-about-fluoride-varnish",
  // "dental-anxiety-in-children",
  // "5-warning-signs-of-dental-emergency-in-children",
  // "athletic-mouth-guards-are-protecting-your-childs-teeth",
  // "everythingthat-you-need-to-know-about-pediatric-dental-fillings",
  // "dental-flossing-for-kids",
  // "how-long-does-a-root-canal-procedure-take",
  // "what-is-root-canal-therapy",
  // "best-food-for-your-kids-from-oral-health",
  // "what-to-expect-when-you-take-your-child-for-a-dental-filling-procedure",
  // "dental-insurance-for-dental-emergencies",
  // "cracked-or-chipped-tooth",
  // "parental-guide-to-prevent-tooth-decay-in-kids",
  // "about-the-pediatric-dentistry-for-adolescents",
  // "why-does-my-child-have-tooth-pain",
  // "tips-to-prevent-tooth-decay-in-kids",
  // "nitrous-oxide-sedation-in-kids-dentistry",
  // "oral-cavities-in-kids",
  // "pediatric-dentistry-for-adolescents",
  // "common-dental-problems-that-children-face",
  // "understanding-wisdom-tooth-removal",
  // "the-differences-between-metal-crowns-and-porcelain-crowns",
  // "how-to-handle-a-dental-emergency",
  // "learn-more-about-pediatric-dentistry",
  // "tooth-extraction-in-kids-cause-and-treatment",
  // "everything-that-you-need-to-know-about-pediatric-dental-fillings",
];

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  async redirects() {
    return paths.map((route) => {
      return {
        source: `/${route.path}`,
        destination: `/${route.des}/${route.path}`,
        permanent: true,
      };
    });
  },
};

module.exports = nextConfig;
